### ISSUE TITLE
Did azure change and ihol got deprecated?

### ISSUE THREAD

**Issue by brunoschroeder** [eikenb/ihol#1]
Dear John.

I also hate microsoft products and outolook. I use vdirsyncer, offlineimap, mutt, khal, khard, etc... I love the prompt and cant stand interacting with microsoft tools.

I was looking forward to use your tool, but it is not working for me, and I guess O356 might need an update.

When follwing O356 instructions when it says "Visit the following url to give consent", the URL did not work.

From the azure / active directory / outlook version used by my current employer, I got an error message saying: 
"AADSTS50194: Application '<id>'(IHOL) is not configured as a multi-tenant application. Usage of the /common endpoint is not supported for such applications created after '10/15/2018'. Use a tenant-specific endpoint or configure the application to be multi-tenant."

---
I found the API endpoints and I was able to access the same URL exchanging "common" for the <tentant-ID>. It redirects me to "https://outlook.office.com/mail/inbox", but when I give it back to python in the terminal, it gives me:

"Unable to fetch auth token. Error: (mismatching_state) CSRF Warning! State not equal in request and response."

---
If I confiure the authentication as multi-tenant, I get the follwoing error:
"AADSTS50011: The reply url specified in the request does not match the reply urls configured for the application: '<id>'."

There is no URL with "common" in it in the azure management dashboard.

---
Another piece of important information: the "nativeclient" link (https://login.microsoftonline.com/common/oauth2/nativeclient) does not seem to work, either passing "common" or "<id>".
I have been passing nothing as that argument or https://outlook.office365.com/owa/

The error I get when I try "nativeclient", exchanging "common" for "<tentant-id>" is:
"AADSTS50011: The reply url specified in the request does not match the reply urls configured for the application: '<id>'. "

---
Can we get from O356 guys some guidance and come to a step by step on how to generate the token and bring it to the file?

Maybe an easy way out for our problem could come from using network inspector in firefox when accessing the URL. - I see some tokens being passed in the header, mixed with the cookies, but I am not quite sure how to move forward from there.

Thank you in advance.

Kind regards,

Bruno

**Comment by brunoschroeder** [comment]
> Dear John.
> 
> I also hate microsoft products and outolook. I use vdirsyncer, offlineimap, mutt, khal, khard, etc... I love the prompt and cant stand interacting with microsoft tools.
> 
> I was looking forward to use your tool, but it is not working for me, and I guess O356 might need an update.
> 
> When follwing O356 instructions when it says "Visit the following url to give consent", the URL did not work.
> 
> From the azure / active directory / outlook version used by my current employer, I got an error message saying:
> "AADSTS50194: Application ''(IHOL) is not configured as a multi-tenant application. Usage of the /common endpoint is not supported for such applications created after '10/15/2018'. Use a tenant-specific endpoint or configure the application to be multi-tenant."
> 
> I found the API endpoints and I was able to access the same URL exchanging "common" for the . It redirects me to "https://outlook.office.com/mail/inbox", but when I give it back to python in the terminal, it gives me:
> 
> "Unable to fetch auth token. Error: (mismatching_state) CSRF Warning! State not equal in request and response."
> 
> If I confiure the authentication as multi-tenant, I get the follwoing error:
> "AADSTS50011: The reply url specified in the request does not match the reply urls configured for the application: ''."
> 
> There is no URL with "common" in it in the azure management dashboard.
> 
> Another piece of important information: the "nativeclient" link (https://login.microsoftonline.com/common/oauth2/nativeclient) does not seem to work, either passing "common" or "".
> I have been passing nothing as that argument or https://outlook.office365.com/owa/
> 
> Can we get from O356 guys some guidance and come to a step by step on how to generate the token and bring it to the file?
> 
> Maybe an easy way out for our problem could come from using network inspector in firefox when accessing the URL. - I see some tokens being passed in the header, mixed with the cookies, but I am not quite sure how to move forward from there.
> 
> Thank you in advance.
> 
> Kind regards,
> 
> Bruno

**Comment by eikenb** [comment]
Hey @brunoschroeder. I subscribed to that ticket you filed and will keep an eye on it to see if there is anything I can do to help. I moved on from that job that used Office365 but would be happy to keep this working if I can. If you or the O365 people figure out a fix/workaround I'll be sure to update things here (or accept a PR). 

I think it is possible to get a personal Office365 account for free and I will look into that if we are close and I just need to test things. But I really don't have time to take it up from scratch right now.

**Comment by MaxWinterstein** [comment]
without further looking how this stuff works, i guess you need to pass the `tenant_id` into your `authenticate()` call at https://github.com/eikenb/ihol/blob/master/initial-auth.py#L16

```diff
- result = acct.authenticate(scopes=scopes)
+ result = acct.authenticate(scopes=scopes, tenant_id='0000-0000....0000')
```

This will change the endpoint from `common` to your `tenant_id` within the O365 Connection class.

**Comment by mhtrinhLIC** [comment]
I recently fork this repo and did some update. @brunoschroeder you can try my repo. If that work for you, I can make a PR to this repo
Edit: my repo is https://github.com/mhtrinhLIC/ihol

**Comment by eikenb** [comment]
@mhtrinhLIC Thanks! I'll try to make some time this weekend to create a free office 365 account and test this out if @brunoschroeder hasn't had a chance to test it by then.

**Comment by eikenb** [comment]
@mhtrinhLIC .. I'm going to create a pull request from your fork to make it easier to test and merge.

**Comment by eikenb** [comment]
Hit a snag. I don't see a 'Directory (tenent) ID' anywhere.  The Overview has an 'Application (client) ID' and an 'Object ID' and that's it. I tried the Object ID just in case, but it didn't work. 

This is with a personal account with the application created through the Azure Portal following the docs on the O365 page.

**Comment by eikenb** [comment]
Looking for `tenant` in the 0365 repo I noticed a use of 'common' as the tenant id. Tried that and it worked.

**Comment by eikenb** [comment]
I'm going to make a few tweaks locally and then merge it. Should have it up tonight.

**Comment by eikenb** [comment]
Ok. I've merged and pushed @mhtrinhLIC changes which fixes this.  I've tested them with a personal office.com account and they worked. I updated the README as well.
